name: CI & Deploy (vac.rw)

on:
  push:
    branches: [ main ]   # Change if your prod branch differs
  workflow_dispatch: {}   # Allow manual runs

concurrency:
  group: deploy-vacrw
  cancel-in-progress: true

jobs:
  ci:
    name: Build (CI)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (LTS) + Yarn cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: Enable Corepack (Yarn)
        run: corepack enable

      - name: Install dependencies
        run: |
          if [ -f .yarnrc.yml ]; then
            echo "Yarn Berry detected"
            yarn install --immutable
          else
            echo "Yarn Classic detected"
            yarn install --frozen-lockfile
          fi

      - name: Build Next.js
        env:
          NEXT_TELEMETRY_DISABLED: '1'
          # Put build-time env here if needed:
          # NEXT_PUBLIC_API_BASE: https://vac.rw/api
        run: yarn build

  deploy:
    name: Deploy to Contabo
    needs: ci
    if: ${{ needs.ci.result == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Recreate private key from base64
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_BASE64 }}" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          chmod 700 ~/.ssh

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Test SSH connectivity (no command)
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP:   ${{ secrets.SERVER_IP }}
        run: |
          ssh -o IdentitiesOnly=yes -i ~/.ssh/id_ed25519 "$SERVER_USER@$SERVER_IP" 'echo "SSH handshake OK"'

      - name: Run remote deploy script
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP:   ${{ secrets.SERVER_IP }}
        run: |
          ssh -o IdentitiesOnly=yes -i ~/.ssh/id_ed25519 "$SERVER_USER@$SERVER_IP" 'bash ~/vacrw/deploy.sh'
